### ISSUE TITLE
Add API to retrieve asset ids which can be used to sign & pay extrinsics

### ISSUE THREAD

**Issue by bvotteler** [interlay/bridge#104]
When signing and sending a transaction, we can provide an option `assetId: AnyNumber` to use that asset to pay for the submitted extrinsic.

eg. to pay for sending USDT from Asset Hub to Interlay, and pay the submission in USDT too, we would submit something like this:
```ts
transaction
            .signAndSend(account, { nonce: -1, assetId: 1984 }, (result: ISubmittableResult) => callback({ unsubscribe, result }))
            .then((u: () => void) => (unsubscribe = u))
            .catch((error) => reject(error));
```
This feature request is to provide an API to get a list of asset ids by token name so the consumer (our UI) can use that number to feed into the `assetId` option.

**Comment by sander2** [comment]
At first I was thinking an API like this:
```ts
type FeeInfo = {
    default: CurrencyId;
    overrides: {
        dexCurrencyId: CurrencyId;
        assetId: number; 
    }[]
}
function getFeeTokens(...): FeeInfo {...}
```

But then again, this override for the assetId is not available on every chain, statemint/e is the only one that I'm aware of that uses this. Other chains, like acala, also allow different currencies, but they're implemented differently (e.g. similar to what we have on our chain, with the withFeeCurrency wrapper). So it's difficult to provide a generalized solution

**Comment by bvotteler** [comment]
Closing issue after internal discussions.

Summary:
Chains implement alternative fees differently. So this type of interface would be of limited use. In fact, currently, we'd only be using it for sending USDT from the Asset Hub to Interlay/Kintsugi.
So the special case will be handled in the UI instead.
