### ISSUE TITLE
Don't rely on hardcoded chains&tokens in chopsticks test

### ISSUE THREAD

**Issue by sander2** [interlay/bridge#64]
> My concern is that we might forget to add that "latest addition" and then run into issues down the line.
Perhaps we can check the static list against the actually implemented we find as we navigate the adapters' routes?
Again: I'm fine with adding that as a todo/issue to be addressed outside of this PR.

_Originally posted by @bvotteler in https://github.com/interlay/bridge/pull/57#discussion_r1134145824_

**Comment by bvotteler** [comment]
PR #89 resolved this
